- repo: https://github.com/terraform-modules-krish/pre-commit
  rev: v0.0.2
  hooks:
    - id: goimports
- repo: local
  hooks:
    - id: test-interfaces-used
      name: test-interfaces-used
      entry: bash -c 'grep -Rw "*testing.T" modules | grep -v _test.go | wc -l'
      language: system
      types: [go]
      pass_filenames: false
